spring:
  datasource:
    url: jdbc:postgresql://auth-postgres-db:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

user-service:
  base-url: http://user-service:8081