server:
  port: 8081

spring:
  application:
    name: user-service


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          preferred_instant_jdbc_type: TIMESTAMP_WITH_TIME_ZONE

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
